### ISSUE TITLE
ران نشدن برنامه

### ISSUE THREAD

**Issue by amirhossein-fzl** [TechWithOmid/shad-bot#1]
من در لینوکسم. پایتون 2.7.18 هم رو سیستم دارم. پایتون 3.8.6 هم دارم. پایتون 3.9.0+ هم دارم. روی هیچ کدوم ران نشد. پیغام های هر ورژن رو میگم :

پایتون 2.7.18

```
File "main.py", line 73
SyntaxError: Non-ASCII character '\xd8' in file main.py on line 73, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

پایتون 3.8.6

```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.4) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/amirhossein/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 31, in <module>
    driver = webdriver.Chrome(PATH, options=options)  # chrome driver settings
  File "/home/amirhossein/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/amirhossein/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

پایتون 3.9.0

```
Traceback (most recent call last):
  File "/home/amirhossein/projects/shad-bot/main.py", line 13, in <module>
    import pyfiglet
ModuleNotFoundError: No module named 'pyfiglet'
```
همه دیپندسی ها رو هم نصب کردم

**Comment by omidmamadi** [comment]
(ببخشید دیر جواب میدم. ولی با توجه به ارور ها و دو حالت بیشتر نیست (من پیشنهاد میکنم که از پایتون ۳.۸ استفاده کنید.
خب حالت اول اینکه ماژول 
pyfiglet
 رو نصب نکرده باشید و شما میگید که دیپندنسی ها نصب هستند

پس از این میگذرم شما یه زحمتی بکشید این راهی رو که میگم رو امتحان کنید و نتیجه رو بهم بگید.
به این لینک برید و درایور کروم رو دانلود کنید :
https://chromedriver.chromium.org/
با توجه به سیستم عامل و ورژن کروم درایور رو دانلود کنید و در مسیری که میگم قرار بدید
/usr/bin/

نکته ای که هست اینکه باید از لینوکس استفاده کنید و باید از کروم استفاده کنید من سعی میکنم در سریع ترین وقت ممکن یه راحل برای اینکار پیدا کنم.

**Comment by jgrooen** [comment]
راه حلش اینه:
`webdriver.Chrome(ChromeDriverManager().install())`
بصورت خودکار خودش درایور رو نصب میکنه

**Comment by omidmamadi** [comment]
لزومی نداره کاری انجام بدی یه بار دیگه پروژه رو از گیتهاب بگیر تغییرات لازم رو توی کد اضافه کردم یبار دیگه دیپندنسی ها رو نصب کن و میتونی استفاده کنی
